name: Run Screener Script

on:
  push:
  workflow_dispatch:

jobs:
  screener:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # ensure we have full history so pushes work
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run screener
        run: python run_screener.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add screener_results.csv
          git commit -m "Update screener results [skip ci]" || echo "No changes to commit"
          git push
